bloodbank/urls.py
from django.contrib import admin
from django.urls import path, include
from blood import views
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('donor/', include('donor.urls')),
    path('patient/', include('patient.urls')),

    path('', views.home_view, name='home'),
    path('logout', LogoutView.as_view(template_name='blood/logout.html'),name='logout'),

    path('afterlogin', views.afterlogin_view,name='afterlogin'),
    path('adminlogin/', LoginView.as_view(template_name='blood/adminlogin.html'), name='adminlogin'),
    path('admin-dashboard/', views.admin_dashboard_view, name='admin-dashboard'),
    path('admin-blood/', views.admin_blood_view, name='admin-blood'),
    path('admin-donor/', views.admin_donor_view, name='admin-donor'),
    path('update-donor/<int:id>', views.update_donor_view, name='update-donor'),
    path('delete-donor/<int:id>', views.delete_donor_view,name='delete-donor'),
    path('admin-patient/', views.admin_patient_view, name='admin-patient'),
    path('update-patient/<int:id>', views.update_patient_view, name='update-patient'),
    path('delete-patient/<int:id>', views.delete_patient_view, name='delete-patient'),
    path('admin-donation/', views.admin_donation_view, name='admin-donation'),
    path('approve-donation/<int:id>', views.approve_donation_view, name='approve-donation'),
    path('reject-donation/<int:id>', views.reject_donation_view, name='reject-donation'),
    path('admin-request', views.admin_request_view, name='admin-request'),
    path('admin-request-history', views.admin_request_history_view, name='admin-request-history'),
    path('update-approve-status/<int:id>', views.update_approve_status_view, name='update-approve-status'),
    path('update-reject-status/<int:id>', views.update_reject_status_view, name='update-reject-status'),
]

donor/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
urlpatterns = [
    path('donorlogin/', LoginView.as_view(template_name="donor/donorlogin.html"), name="donorlogin"),
    path('donorsignup/', views.donor_signup_view, name="donorsignup"),
    path('donor-dashboard/', views.donor_dashboard_view, name="donor-dashboard"),
    path('donate-blood/', views.donate_blood_view, name="donate-blood"),
    path('donation-history/', views.donation_history_view, name="donation-history"),
    path('make-request/', views.make_request_view, name='make-request'),
    path('request-history/', views.request_history_view, name='request-history'),
]

patient/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
urlpatterns = [
    path('patientlogin/', LoginView.as_view(template_name='patient/patientlogin.html'),name='patientlogin'),
    path('patientsignup/', views.patient_signup_view,name='patientsignup'),
    path('patient-dashboard/', views.patient_dashboard_view,name='patient-dashboard'),
    path('make-request/', views.make_request_view, name='make-request'),
    path('my-request/', views.my_request_view, name='my-request'),
]

blood/models.py
from django.db import models
from patient import models as pmodels
from donor import models as dmodels

# Create your models here.

class Stock(models.Model):
    bloodgroup = models.CharField(max_length=10)
    unit = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.bloodgroup
    
class BloodRequest(models.Model):
    request_by_patient=models.ForeignKey(pmodels.Patient, null=True, on_delete=models.CASCADE)
    request_by_donor=models.ForeignKey(dmodels.Donor,null=True,on_delete=models.CASCADE)
    patient_name=models.CharField(max_length=30)
    patient_age=models.PositiveIntegerField()
    reason=models.CharField(max_length=500)
    bloodgroup=models.CharField(max_length=10)
    unit=models.PositiveIntegerField(default=0)
    status=models.CharField(max_length=20,default="Pending")
    date=models.DateField(auto_now=True)
    def __str__(self):
        return self.bloodgroup

patient/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Patient(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='profile_pic/Patient/', null=True, blank=True)

    age=models.PositiveIntegerField()
    bloodgroup=models.CharField(max_length=10)
    disease=models.CharField(max_length=50)
    doctorname=models.CharField(max_length=50)

    address=models.CharField(max_length=40)
    mobile=models.CharField(max_length=20, null=False)

    @property
    def get_name(self):
        return self.user.first_name+ " " + self.user.last_name
    @property
    def get_instance(self):
        return self
    def __str__(self):
        return self.user.first_name

patient/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class PatientUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password']

class PatientForm(forms.ModelForm):
    class Meta:
        model=models.Patient
        fields=['age','bloodgroup','disease','address','doctorname','mobile','profile_pic']

patient/views.py
from django.shortcuts import render
from . import forms, models
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from blood import models as bmodels
from blood import forms as bforms

# Create your views here.

def patient_signup_view(request):
    userForm=forms.PatientUserForm()
    patientForm=forms.PatientForm()
    mydict={'userForm':userForm,'patientForm':patientForm}
    if request.method=='POST':
        userForm = forms.PatientUserForm(request.POST)
        patientForm = forms.PatientForm(request.POST, request.FILES)
        if userForm.is_valid() and patientForm.is_valid():
            user = userForm.save()
            user.first_name = userForm.cleaned_data['first_name']
            user.last_name = userForm.cleaned_data['last_name']
            user.username = userForm.cleaned_data['username']
            user.password = userForm.cleaned_data['password']
            user.set_password(user.password)
            user.save()
            patient = patientForm.save(commit=False)
            patient.user = user
            patient.age = patientForm.cleaned_data['age']
            patient.disease = patientForm.cleaned_data['disease']
            patient.address = patientForm.cleaned_data['address']
            patient.doctorname = patientForm.cleaned_data['doctorname']
            patient.mobile = patientForm.cleaned_data['mobile']
            patient.bloodgroup=patientForm.cleaned_data['bloodgroup']
            patient.save()
            my_patient_group = Group.objects.get_or_create(name='PATIENT')
            my_patient_group[0].user_set.add(user)
        return HttpResponseRedirect('../patientlogin')
    return render(request, 'patient/patientsignup.html', context=mydict)

def patient_dashboard_view(request):
    patient= models.Patient.objects.get(user_id=request.user.id)
    dict={
        'requestpending': bmodels.BloodRequest.objects.all().filter(request_by_patient=patient).filter(status='Pending').count(),
        'requestapproved': bmodels.BloodRequest.objects.all().filter(request_by_patient=patient).filter(status='Approved').count(),
        'requestmade': bmodels.BloodRequest.objects.all().filter(request_by_patient=patient).count(),
        'requestrejected': bmodels.BloodRequest.objects.all().filter(request_by_patient=patient).filter(status='Rejected').count(),
    }
    return render(request,'patient/patient_dashboard.html',context=dict)

def make_request_view(request):
    request_form = bforms.RequestForm()
    mydict={'request_form' : request_form}
    if request.method == 'POST': 
        request_form = bforms.RequestForm(request.POST)
        if request_form.is_valid():
            blood_request=request_form.save(commit=False)
            blood_request.bloodgroup=request_form.cleaned_data['bloodgroup']
            patient=models.Patient.objects.get(user_id=request.user.id)
            blood_request.request_by_patient=patient
            blood_request.save()
            return HttpResponseRedirect('../my-request')
    return render(request,'patient/makerequest.html', context=mydict)

def my_request_view(request):
    patient= models.Patient.objects.get(user_id=request.user.id)
    blood_request=bmodels.BloodRequest.objects.all().filter(request_by_patient=patient)
    return render(request,'patient/my_request.html',{'blood_request':blood_request})

templates/patient/makerequest.html
{% extends 'patient/patientbase.html' %}
{% block content %}
{%load static%}
<head>
        <!-- Font special for pages-->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

        <!-- Main CSS-->
    
        <link href="{% static "css/main.css" %}"rel="stylesheet" media="all">
</head>
<div class="page-wrapper bg-gra-03 p-t-45 p-b-50">
    <div class="wrapper wrapper--w790">
      
        <div style="margin-left: 70px;" class="card card-5">
            <div class="card-heading">
                <h2 class="title">MAKE BLOOD REQUEST</h2>
            </div>
            <div class="card-body">
                <form method="POST" autocomplete="off" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-row">
                        <div class="name">Patient Name</div>
                        <div class="value">
                            <div class="input-group">
                                <input type="text" name="patient_name" id="id_patient_name" required class="input--style-5">
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Patient Age</div>
                        <div class="value">
                            <div class="input-group">
                                <input type="text" name="patient_age" id="id_patient_age" required class="input--style-5">
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Reason</div>
                        <div class="value">
                            <div class="input-group">
                                <input type="text" name="reason" id="id_reason" required class="input--style-5">
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Blood Group</div>
                        <div class="value">
                            <div class="input-group">
                                <div class="rs-select2 js-select-simple select--no-search">
                                    <select name="bloodgroup">
                                        <option disabled="disabled" selected="selected">Choose option</option>
                                        <option>O+</option>
                                        <option>O-</option>
                                        <option>A+</option>
                                        <option>A-</option>
                                        <option>B+</option>
                                        <option>B-</option>
                                        <option>AB+</option>
                                        <option>AB-</option>
                                    </select>
                                    <div class="select-dropdown"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Unit (in ml)</div>
                        <div class="value">
                            <div class="input-group">
                                <input type="text" name="unit" id="id_unit" required class="input--style-5">
                            </div>
                        </div>
                    </div>

                    




                    <div>
                        <button class="btn btn--radius-2 btn-danger" type="submit">REQUEST</button>
                    </div>
                </form>
                <br>
                

            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/patient/my_request.html
{% extends 'patient/patientbase.html' %}
{% block content %}
{%load static%}

<head>
    <style>
        .label {
     color: white;
     padding: 8px;
   }
   
   .success {background-color: #4CAF50;} /* Green */
   .info {background-color: #2196F3;} /* Blue */
   .warning {background-color: #ff9800;} /* Orange */
   .danger {background-color: #f44336;} /* Red */
   .other {background-color: #e7e7e7; color: black;} /* Gray */
    </style>
   </head>
<br><br>
<div class="container">
    <H4 class="text-center">My Blood Request</H4><br>
    <table class="table table-light table-hover table-bordered table-striped">
        <thead class="bg-info">
            <tr>
                <th scope="col">Patient Name</th>
                <th scope="col">Patient Age</th>
                <th scope="col">Reason</th>
                <th scope="col">Blood Group</th>
                <th scope="col">Unit</th>
                <th scope="col">Date</th>
                <th scope="col">Status</th>
                
            </tr>
        </thead>
        <tbody>
            {% for t in blood_request %}
            <tr>
                <td> {{t.patient_name}}</td>
                
                <td>{{t.patient_age}}</td>
                <td>{{t.reason}}</td>
                <td>{{t.bloodgroup}}</td>
                <td>{{t.unit}}</td>
                <td>{{t.date}}</td>
                {% if t.status == 'Approved' %}
                <td><span class="label warning"> Approved</span></td>
                
                {% elif t.status == 'Rejected' %}
                <td><span class="label success">Rejected</span></td>
                {% else %}
                <td><span style="color: white;margin-left: 0px;" class="label info">Pending</span></td>
                {% endif %}
                

            </tr>
            {% endfor %}

        </tbody>
    
    </table>
</div>


{% endblock content %}

templates/patient/patient_dashboard.html
{% extends 'patient/patientbase.html' %}
{% block content %}
<head>
    <style>
            .xyz{     
        color: blue; 
        font-size: 3ex;   
    }
    </style>
</head>
<br><br>
<div class="container">

 
    <div class="row">
      <div class="col-sm-3">
        <div class="card bg-light">
          <div class="card-body">
              <div class="blood">
                <i class="fas fa-sync-alt xyz"></i>
              </div><br>
              <div>
                Request Made <br>
                  {{requestmade}}
              </div>                            
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="card bg-light">
            <div class="card-body">
                <div class="blood">
                  <i class="fas fa-sync xyz"></i>
                </div><br>
                <div>
                    Pending Request <br>
                    {{requestpending}}
                </div>                            
            </div>
          </div>
      </div>

      <div class="col-sm-3">
          <div class="card bg-light">
              <div class="card-body">
                  <div class="blood">
                    <i class="fas fa-check-circle xyz"></i>
                  </div><br>
                  <div>
                       Approved Request<br>
                      {{requestapproved}}
                  </div>                            
              </div>
            </div>
      </div>
      <div class="col-sm-3">
          <div class="card bg-light">
              <div class="card-body">
                  <div class="blood">
                    <i class="fas fa-times-circle xyz"></i>
                  </div><br>
                  <div>
                       Rejected Request <br>
                      {{requestrejected}}
                  </div>                            
              </div>
            </div>
        </div>

    </div>
</div>


{% endblock content %}

templates/patient/patientbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PATIENT</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.css">

    <style>



 

    .row{
        padding: 5px;
    }
    .fa-tint{     
        color: red;    
    }
    .blood{
        float: right;
    }
    .fa-users{     
        color: blue; 
        font-size: 3ex;   
    }
    .fa-spinner{     
        color: blue; 
        font-size: 3ex;   
    }
    .fa-check-circle{     
        color: blue; 
        font-size: 3ex;   
    }
    .xyz{     
        color: blue; 
        font-size: 3ex;   
    }

*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  list-style: none;
  text-decoration: none;
  font-family: 'Josefin Sans', sans-serif;
}

body{
   background-color: #f3f5f9;
}
.bg-danger {
    background-color: #ff0018!important;
}

.wrapper{
  display: flex;
  position: relative;
}

.wrapper .sidebar{
  width: 200px;
  height: 100%;
  background: #343a40;
  padding: 30px 0px;
  position: fixed;
}

.wrapper .sidebar h2{
  color: #fff;
  text-transform: uppercase;
  text-align: center;
  margin-bottom: 30px;
}

.wrapper .sidebar ul li{
  padding: 15px;
  border-bottom: 1px solid #bdb8d7;
  border-bottom: 1px solid rgba(0,0,0,0.05);
  border-top: 1px solid rgba(255,255,255,0.05);
}    

.wrapper .sidebar ul li a{
  color: #bdb8d7;
  display: block;
}

.wrapper .sidebar ul li a .fas{
  width: 25px;
}

.wrapper .sidebar ul li:hover{
  background-color: #594f8d;
}
    
.wrapper .sidebar ul li:hover a{
  color: #fff;
}
 
.wrapper .sidebar .social_media{
  position: absolute;
  bottom: 0;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
}

.wrapper .sidebar .social_media a{
  display: block;
  width: 40px;
  background: #594f8d;
  height: 40px;
  line-height: 45px;
  text-align: center;
  margin: 0 5px;
  color: #bdb8d7;
  border-top-left-radius: 5px;
  border-top-right-radius: 5px;
}

.wrapper .main_content{
  width: 100%;
  margin-left: 200px;
}

.wrapper .main_content .header{
  padding: 20px;
  background: #fff;
  color: #717171;
  border-bottom: 1px solid #e0e4e8;
}

.wrapper .main_content .info{
  margin: 20px;
  color: #717171;
  line-height: 25px;
}

.wrapper .main_content .info div{
  margin-bottom: 20px;
}

@media (max-height: 500px){
  .social_media{
    display: none !important;
  }
}
.fa-sign-out-alt{
    color: white;
    font-size: 2ex;
}

    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-danger">
        <a style="color:white;" class="navbar-brand" href="/"><i class="fab fa-gratipay"></i>&nbsp;<font face = "Comic sans MS" size ="4">Blood Bank Management System</font></a>
        
      
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" style="color: white;" href="/logout">Logout &nbsp; <i class="fas fa-sign-out-alt"></i></a>
                </li>
                
            </ul>
        </div>
      </nav>
<br><br>
<div class="wrapper">
    <div class="sidebar">
        
        <ul>
            <li><a style="text-decoration:none;" href="/"><i class="fas fa-home"></i>Home</a></li>
            <li><a style="text-decoration:none;" href="/patient/make-request"><i class="fas fa-sync-alt"></i>Make Request</a></li>
            <li><a style="text-decoration:none;" href="/patient/my-request"><i class="fas fa-history"></i>Request History</a></li>

        </ul> 

    </div>
    <div class="main_content">


{% block content %}

{% endblock content %}



    </div>
</div>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/patient/patientlogin.html
{%load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
      
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.css">
 
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Main CSS-->
    <link href="{% static "css/main.css" %}"rel="stylesheet" media="all">
    <style>

    </style>
  </head>
  <body>
    {% include "blood/navbar.html" %}




    <div class="page-wrapper bg-gra-03 p-t-45 p-b-50">
        <div class="wrapper wrapper--w790">
            <br><br><br>
            <div class="card card-5">
                <div class="card-heading">
                    <h2 class="title">Patient Login</h2>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="name">Username</div>
                            <div class="value">
                                <div class="input-group">
                                    <input type="text" name="username" class="input--style-5">
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Password</div>
                            <div class="value">
                                <div class="input-group">
                                    <input type="password" name="password" class="input--style-5">
                                </div>
                            </div>
                        </div>


                        

                        <div>
                            <button class="btn btn--radius-2 btn-danger" type="submit">Login</button>
                        </div>
                    </form>
                    <br>
                    <p style="text-align: center;">Does not have an account ? <a style="text-decoration: none;" href="/patient/patientsignup">Click here to register</a></p>

                </div>
            </div>
        </div>
    </div>

{% include "blood/footer.html" %}
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>